name: Add shadcn Components

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  add-components:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the Node.js version if required

      # Step 3: Install dependencies and add components
      - name: Add shadcn Components
        run: |
          # Initialize shadcn
          npx shadcn@latest init

          # Define the list of components
          components=(
            accordion
            alert
            alert-dialog
            aspect-ratio
            avatar
            badge
            breadcrumb
            button
            calendar
            card
            carousel
            chart
            checkbox
            collapsible
            combobox
            command
            context-menu
            data-table
            date-picker
            dialog
            drawer
            dropdown-menu
            form
            hover-card
            input
            input-otp
            label
            menubar
            navigation-menu
            pagination
            popover
            progress
            radio-group
            resizable
            scroll-area
            select
            separator
            sheet
            skeleton
            slider
            sonner
            switch
            table
            tabs
            textarea
            toast
            toggle
            toggle-group
            tooltip
          )

          # Add each component using a loop
          for component in "${components[@]}"
          do
            npx shadcn@latest add "$component"
          done
